# Generated by Django 5.2.17 on 2026-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
