# Generated by Django 5.2.17 on 2026-08-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_table_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
