# Generated by Django 5.2.17 on 2026-08-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_border',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
