# Generated by Django 6.0.3 on 2026-03-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('running', 'Running'), ('finished', 'Finished')], default='lobby', max_length=10)),
                ('starting_chips', models.IntegerField(default=10000)),
                ('max_players', models.IntegerField(default=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlindLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('small_blind', models.IntegerField()),
                ('big_blind', models.IntegerField()),
                ('ante', models.IntegerField(default=0)),
                ('duration_hands', models.IntegerField(default=8)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('chips', models.IntegerField()),
                ('finish_position', models.IntegerField(blank=True, null=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tournament', 'seat'), ('tournament', 'user')},
            },
        ),
    ]
