# Generated by Django 6.0.3 on 2026-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindlevel',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blindlevel',
            name='duration_hands',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
