# Generated by Django 6.0.3 on 2026-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_add_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_rebuys',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='late_reg_level',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_rebuys',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_level',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='rebuy_count',
            field=models.IntegerField(default=0),
        ),
    ]
