# Generated by Django 6.0.3 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournament_allow_rebuys_tournament_late_reg_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blindlevel",
            name="is_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="players_per_table",
            field=models.IntegerField(default=9),
        ),
    ]