# Generated by Django 6.0.3 on 2026-04-20 00:00

from django.db import migrations, models
import django.db.models.deletion


def backfill_table_assignments(apps, schema_editor):
    Tournament = apps.get_model("tournaments", "Tournament")
    TournamentPlayer = apps.get_model("tournaments", "TournamentPlayer")
    TournamentTable = apps.get_model("tournaments", "TournamentTable")

    for tournament in Tournament.objects.all():
        player_count = TournamentPlayer.objects.filter(tournament=tournament).count()
        total_players = max(player_count, 1)
        required_tables = ((total_players - 1) // tournament.players_per_table) + 1

        tables_by_number = {}
        for table_number in range(1, required_tables + 1):
            table, _ = TournamentTable.objects.get_or_create(
                tournament=tournament,
                table_number=table_number,
                defaults={"max_seats": tournament.players_per_table, "is_active": True},
            )
            tables_by_number[table_number] = table

        for player in TournamentPlayer.objects.filter(tournament=tournament).order_by("seat"):
            table_number = (player.seat // tournament.players_per_table) + 1
            player.table = tables_by_number[table_number]
            player.seat_at_table = player.seat % tournament.players_per_table
            player.save(update_fields=["table", "seat_at_table"])


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_tournament_players_per_table_blindlevel_is_break"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_number", models.IntegerField()),
                ("max_seats", models.IntegerField(default=9)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tournament", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tables", to="tournaments.tournament")),
            ],
            options={
                "ordering": ["table_number"],
                "unique_together": {("tournament", "table_number")},
            },
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="seat_at_table",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="table",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="players", to="tournaments.tournamenttable"),
        ),
        migrations.RunPython(backfill_table_assignments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="tournamentplayer",
            constraint=models.UniqueConstraint(fields=("table", "seat_at_table"), name="unique_table_local_seat"),
        ),
    ]