# Generated by Django 5.2.17 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_backfill_winner_finish_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='time_bank_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
