# Generated by Django 5.2.17 on 2026-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournament_time_bank_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_level_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hands_in_level',
            field=models.IntegerField(default=0),
        ),
    ]
