# Generated by Django 6.1 on 2026-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournament_buy_in_cents_settlement_ledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rabbit_hunting_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
