# Generated by Django 5.2.17 on 2026-08-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_tournament_rabbit_hunting_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='bounty_prize_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bounty_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bounty_mode',
            field=models.CharField(choices=[('none', 'No bounties'), ('fixed', 'Fixed knockout'), ('progressive', 'Progressive knockout')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bounty_progressive_split_pct',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='bounty_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='bounty_won_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='knockouts',
            field=models.IntegerField(default=0),
        ),
    ]
