# Generated by Django 5.2.17 on 2026-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_ledgerentry_bounty_prize_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='showdown_seconds',
            field=models.IntegerField(default=5),
        ),
    ]
