# Generated by Django 5.2.17 on 2026-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournament_showdown_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('nlh', "No-Limit Hold'em")], default='nlh', max_length=8),
        ),
    ]
