# Generated by Django 5.2.17 on 2026-08-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournament_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
