# Generated by Django 5.2.17 on 2026-08-16 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('tournaments', '0021_default_table_of_eight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='clubs.season'),
        ),
    ]
