# Generated by Django 5.2.17 on 2026-08-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_tournament_club_tournament_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_rebuys',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
