# Generated by Django 5.2.17 on 2026-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_alter_tournament_max_rebuys'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='buy_in_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('standard', 'Tournament'), ('spingo', 'Spin n Go')], default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='spin_multiplier',
            field=models.IntegerField(default=0),
        ),
    ]
