# Generated by Django 5.2.17 on 2026-08-19 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def lock_in_current_debts(apps, schema_editor):
    """Write down the pairings players are already acting on.

    Everything owed up to now was only ever a suggestion recomputed on each
    read. Whatever it says today is what people have been looking at, so that is
    what gets written down — deliberately spelled out here rather than imported
    from tournaments.ledger, which is free to change after this migration.
    """
    LedgerEntry = apps.get_model("tournaments", "LedgerEntry")
    Settlement = apps.get_model("tournaments", "Settlement")
    DebtTransfer = apps.get_model("tournaments", "DebtTransfer")

    if DebtTransfer.objects.exists():
        return

    totals = {}
    for entry in LedgerEntry.objects.values("user_id", "stake_cents", "prize_cents"):
        totals[entry["user_id"]] = (
            totals.get(entry["user_id"], 0) + entry["prize_cents"] - entry["stake_cents"]
        )
    for row in Settlement.objects.values("from_user_id", "to_user_id", "amount_cents"):
        totals[row["from_user_id"]] = totals.get(row["from_user_id"], 0) + row["amount_cents"]
        totals[row["to_user_id"]] = totals.get(row["to_user_id"], 0) - row["amount_cents"]

    debtors = sorted(
        ([user_id, -cents] for user_id, cents in totals.items() if cents < 0),
        key=lambda row: -row[1],
    )
    creditors = sorted(
        ([user_id, cents] for user_id, cents in totals.items() if cents > 0),
        key=lambda row: -row[1],
    )

    transfers = []
    i = j = 0
    while i < len(debtors) and j < len(creditors):
        amount = min(debtors[i][1], creditors[j][1])
        if amount > 0:
            transfers.append(
                DebtTransfer(
                    from_user_id=debtors[i][0],
                    to_user_id=creditors[j][0],
                    amount_cents=amount,
                )
            )
        debtors[i][1] -= amount
        creditors[j][1] -= amount
        if debtors[i][1] == 0:
            i += 1
        if creditors[j][1] == 0:
            j += 1

    DebtTransfer.objects.bulk_create(transfers)


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_spingo_and_coin_buy_ins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('paid_cents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_owed', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_due', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(lock_in_current_debts, migrations.RunPython.noop),
    ]
