# Generated by Django 5.2.17 on 2026-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_debt_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('standard', 'Tournament'), ('spingo', 'Spin n Go'), ('sitngo', 'Sit n Go')], default='standard', max_length=12),
        ),
    ]
