# Generated by Django 5.2.17 on 2026-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_sit_n_go_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mystery_envelopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mystery_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mystery_release',
            field=models.CharField(choices=[('itm', 'When the money is reached'), ('reg_closed', 'When registration closes')], default='itm', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bounty_mode',
            field=models.CharField(choices=[('none', 'No bounties'), ('fixed', 'Fixed knockout'), ('progressive', 'Progressive knockout'), ('mystery', 'Mystery bounty')], default='none', max_length=12),
        ),
    ]
