# Generated by Django 5.2.17 on 2026-08-22 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('tournaments', '0027_mystery_bounty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='occurs_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('weekday', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('days_ahead', models.IntegerField(default=4)),
                ('template', models.JSONField(blank=True, default=dict)),
                ('levels', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='clubs.club')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='clubs.season')),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournaments.fixture'),
        ),
    ]
