# Generated by Django 5.2.17 on 2026-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_tournament_occurs_on_fixture_tournament_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mystery_winner_keeps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('standard', 'Tournament'), ('spingo', 'Spin n Go'), ('sitngo', 'Sit n Go'), ('allinfold', 'All In or Fold')], default='standard', max_length=12),
        ),
    ]
