# Generated by Django 5.2.17 on 2026-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_tournament_mystery_winner_keeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='timezone_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
