# Generated by Django 5.2.17 on 2026-08-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_fixture_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mystery_cut',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
