# Generated by Django 5.2.17 on 2026-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_tournament_mystery_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='payout_share_pct',
            field=models.IntegerField(default=0),
        ),
    ]
