# Generated by Django 5.2.17 on 2026-08-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_tournament_payout_share_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TournamentSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='tournaments.tournament')),
            ],
        ),
    ]
