# Generated by Django 5.2.17 on 2026-08-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegames', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinledger',
            name='reason',
            field=models.CharField(choices=[('signup', 'Opening balance'), ('daily', 'Daily coins'), ('stake', 'Side game stake'), ('payout', 'Side game payout'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('mission', 'Mission reward')], max_length=16),
        ),
        migrations.CreateModel(
            name='MissionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=32)),
                ('period', models.CharField(max_length=16)),
                ('coins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'mission', 'period'), name='one_claim_per_mission_period')],
            },
        ),
    ]
