# Generated by Django 5.2.17 on 2026-08-28 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegames', '0002_alter_coinledger_reason_missionclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(default=0)),
                ('deck', models.JSONField(blank=True, default=list)),
                ('dealer', models.JSONField(blank=True, default=list)),
                ('hands', models.JSONField(blank=True, default=list)),
                ('active', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('playing', 'In play'), ('finished', 'Finished')], default='playing', max_length=10)),
                ('net', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackjack_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'playing')), fields=('user',), name='one_open_blackjack_round')],
            },
        ),
    ]
