# Generated by Django 5.2.17 on 2026-08-29 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegames', '0003_blackjackround'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=32, unique=True)),
                ('phase', models.CharField(choices=[('betting', 'Betting'), ('playing', 'Playing'), ('settling', 'Settling')], default='betting', max_length=10)),
                ('phase_ends_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('round_number', models.IntegerField(default=0)),
                ('deck', models.JSONField(blank=True, default=list)),
                ('dealer', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlackjackSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('bet', models.IntegerField(default=0)),
                ('hands', models.JSONField(blank=True, default=list)),
                ('net', models.IntegerField(default=0)),
                ('idle_rounds', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackjack_seats', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='sidegames.blackjacktable')),
            ],
            options={
                'ordering': ['seat'],
                'constraints': [models.UniqueConstraint(fields=('table', 'seat'), name='one_player_per_blackjack_seat'), models.UniqueConstraint(fields=('table', 'user'), name='one_blackjack_seat_per_player')],
            },
        ),
    ]
