# Generated by Django 5.2.17 on 2026-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegames', '0004_blackjacktable_blackjackseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackjackseat',
            name='planned',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='blackjacktable',
            name='turn',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
