# Generated by Django 6.0.3 on 2026-03-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.IntegerField()),
                ('level_index', models.IntegerField()),
                ('dealer_seat', models.IntegerField()),
                ('community_cards', models.JSONField(default=list)),
                ('pot_total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('preflop', 'Pre-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('complete', 'Complete')], default='preflop', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='HandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(choices=[('preflop', 'Pre-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River')], max_length=10)),
                ('action', models.CharField(choices=[('fold', 'Fold'), ('check', 'Check'), ('call', 'Call'), ('bet', 'Bet'), ('raise', 'Raise'), ('blind', 'Blind'), ('ante', 'Ante')], max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.hand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentplayer')),
            ],
        ),
    ]
