# Generated by Django 5.2.17 on 2026-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_hand_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='handaction',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
