# Generated by Django 5.2.17 on 2026-08-23 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('stake', models.CharField(choices=[('micro', '1/2'), ('low', '2/5'), ('mid', '5/10'), ('high', '10/25'), ('nose', '25/50')], max_length=12)),
                ('seat_count', models.IntegerField(choices=[(2, '2-max'), (6, '6-max'), (9, '9-max')], default=6)),
                ('run_it_twice', models.BooleanField(default=False)),
                ('bomb_pot_every', models.IntegerField(default=0)),
                ('bomb_pot_bb', models.IntegerField(default=2)),
                ('rabbit_hunting', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hand_at', models.DateTimeField(blank=True, null=True)),
                ('hands_played', models.IntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_tables', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stake', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.IntegerField()),
                ('pot', models.IntegerField(default=0)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('boards', models.JSONField(blank=True, default=list)),
                ('was_bomb_pot', models.BooleanField(default=False)),
                ('ran_twice', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='cash.cashtable')),
            ],
            options={
                'ordering': ['-played_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('stack', models.IntegerField(default=0)),
                ('sitting_out', models.BooleanField(default=False)),
                ('leaving', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bought_in', models.IntegerField(default=0)),
                ('hands_dealt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_seats', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken', to='cash.cashtable')),
            ],
            options={
                'ordering': ['table_id', 'seat'],
                'constraints': [models.UniqueConstraint(fields=('table', 'seat'), name='one_player_per_cash_seat'), models.UniqueConstraint(fields=('table', 'user'), name='one_seat_per_player')],
            },
        ),
    ]
