# Generated by Django 5.2.17 on 2026-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_public_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtable',
            name='seat_count',
            field=models.IntegerField(choices=[(2, '2-max'), (6, '6-max'), (8, '8-max'), (9, '9-max')], default=6),
        ),
    ]
