# Generated by Django 5.2.17 on 2026-08-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_four_public_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtable',
            name='stake',
            field=models.CharField(choices=[('micro', '1/2'), ('low', '2/5'), ('mid', '5/10'), ('high', '10/20'), ('nose', '25/50')], max_length=12),
        ),
        migrations.CreateModel(
            name='CashHandSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('net', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cash.cashhand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_hand_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at', '-id'],
                'indexes': [models.Index(fields=['user', 'played_at'], name='cash_cashha_user_id_f66eac_idx')],
            },
        ),
    ]
