# Generated by Django 5.2.17 on 2026-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_alter_cashtable_stake_cashhandseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashseat',
            name='away_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
